name: blurry_side_sheet
description: This Flutter package provides a Material Design 3 modal side sheet widget with blur background.
version: 0.0.1
repository: https://github.com/hyperion2144/blurry_side_sheet
issue_tracker: https://github.com/hyperion2144/blurry_side_sheet/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'This screenshot shows the thumbnail of the package'
    path: assets/Material design 3 side sheet.jpg

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  flutter:
    sdk: flutter

